/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmartTooltip {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLSmartTooltipElement extends Components.SmartTooltip, HTMLStencilElement {
    }
    var HTMLSmartTooltipElement: {
        prototype: HTMLSmartTooltipElement;
        new (): HTMLSmartTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "smart-tooltip": HTMLSmartTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SmartTooltip {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "smart-tooltip": SmartTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smart-tooltip": LocalJSX.SmartTooltip & JSXBase.HTMLAttributes<HTMLSmartTooltipElement>;
        }
    }
}
