/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmartTooltip {
        /**
          * Tooltip text to be displayed when open.
         */
        "tooltipText": string;
    }
}
declare global {
    interface HTMLSmartTooltipElement extends Components.SmartTooltip, HTMLStencilElement {
    }
    var HTMLSmartTooltipElement: {
        prototype: HTMLSmartTooltipElement;
        new (): HTMLSmartTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "smart-tooltip": HTMLSmartTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SmartTooltip {
        /**
          * Tooltip text to be displayed when open.
         */
        "tooltipText"?: string;
    }
    interface IntrinsicElements {
        "smart-tooltip": SmartTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smart-tooltip": LocalJSX.SmartTooltip & JSXBase.HTMLAttributes<HTMLSmartTooltipElement>;
        }
    }
}
